name: artfolio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.16.0
  firebase_analytics: ^10.10.0
  firebase_core: ^2.28.0
  firebase_messaging: ^14.8.0
  google_fonts: ^6.2.1
  firebase_auth: ^4.18.0
  intl: ^0.19.0
  datetime_picker_formfield_new: ^2.1.0
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
